<?php

use CodeIgniter\Router\RouteCollection;

/**
 * @var RouteCollection $routes
 */

// Default route settings (leave as generated by CodeIgniter)
$routes->setDefaultNamespace('App\Controllers');
$routes->setDefaultController('Pages');
$routes->setDefaultMethod('landing');
$routes->setTranslateURIDashes(false);
$routes->set404Override();
$routes->setAutoRoute(false); // keep this false and register routes explicitly, as below

/*
 * --------------------------------------------------------------------
 * App Routes
 * --------------------------------------------------------------------
 * The default CodeIgniter welcome route has been removed.
 */
$routes->get('/', 'Pages::landing');
$routes->get('about', 'Pages::about');
$routes->get('customers', 'Customers::index');
$routes->get('users', 'Users::index');
